apiVersion: v1
data:
  tls.crt:
  tls.key:
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/cert-dubyatp-xyz
    replicator.v1.mittwald.de/replicated-keys: tls.crt,tls.key
  name: cert-dubyatp-xyz
type: Opaque