apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: gitea-runner
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: buildkitd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
      - args:
        - --addr
        - tcp://0.0.0.0:1234
        image: moby/buildkit:v0.27.1
        imagePullPolicy: Always
        name: buildkitd
        ports:
        - containerPort: 1234
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30