apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: gitea-runner
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 1234
  selector:
    app: buildkitd