apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-config
data:
  config.yaml: |-
    log:
      level: info
    runner:
      file: /data/.runner
      capacity: 1
      env_file: .env
      timeout: 3h
      shutdown_timeout: 0s
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - "ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest"
        - "ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04"
        - "ubuntu-20.04:docker://docker.gitea.com/runner-images:ubuntu-20.04"
    cache:
      enabled: true
      dir: ""
      host: ""
      port: 0
      external_server: ""
    container:
      network: "bridge"
      privileged: false
      options: "--dns 10.112.0.10"
      workdir_parent: /scratch
      valid_volumes:
        - /scratch/**
      docker_host: ""
      force_pull: true
      force_rebuild: false
      require_docker: false
      docker_timeout: 0s
    host:
      workdir_parent: