apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gita-runner-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: weyma-shared
