apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: weyma-vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden
        property: admin_token
    - secretKey: HIBP_API_KEY
      remoteRef:
        key: vaultwarden
        property: hibp_api_key
    - secretKey: SMTP_PASSWORD_OLD
      remoteRef:
        key: vaultwarden
        property: smtp_password
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: vaultwarden
        property: smtp_password_smtp2go