apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-pvc
spec:
  storageClassName: weyma-shared
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
