apiVersion: v1
kind: ConfigMap
metadata:
  name: attic-config
data:
  server.toml: |
    listen = "[::]:8080"
    allowed-hosts = []

    #api-endpoint = "https://nix-cache.dubyatp.xyz/"

    [database]
    url = "sqlite:///var/empty/.local/share/attic/server.db"

    [storage]
    path = "/data/.local/share/attic/storage"
    type = "local"
    #region = "us-east-1"
    #bucket = "attic-bucket"
    #endpoint = "https://weyma-s3.infra.dubyatp.xyz"

    [chunking]
    nar-size-threshold = 65536
    min-size = 16384
    avg-size = 65536
    max-size = 262144

    [compression]
    type = "zstd"

    [garbage-collection]
    interval = "12 hours"

    [jwt]

    [jwt.signing]
