apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attic-pvc
spec:
  storageClassName: weyma-shared
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
