apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: attic-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: weyma-vault
    kind: ClusterSecretStore
  target:
    name: attic-secret
    creationPolicy: Owner
  data:
    - secretKey: ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64
      remoteRef:
        key: attic
        property: ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64