{{- if .Values.externalSecretsManaged }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "wekan.fullname" . }}-extsecret
spec:
  data:
  {{- if .Values.externalSecrets.secrets }}
  {{- range $key := .Values.externalSecrets.secrets }}
  {{- if $key.keyName }}
    - secretKey: {{ $key.secretKeyName }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $key.keyName }}
        metadataPolicy: None
        property: {{ $key.property }}
  {{- end }}
  {{- end }}
  {{- else }}
  {{- fail "externalSecrets.secrets must be defined when externalSecretsManaged is true" }}
  {{- end }}
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStore.kind }}
    name: {{ .Values.externalSecrets.secretStore.name }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ .Values.externalSecrets.targetSecretName }}
{{- end }}