apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nextcloud
            image: nextcloud:28.0.3-apache
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl https://nextcloud.dubyatp.xyz/cron.php
          restartPolicy: OnFailure