apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cloudnativepg
      metadataPolicy: None
      property: immich_pw
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: weyma-vault
  target:
    template:
      data:
        username: immich
        password: "{{ .password }}"
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgres-credentials