apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peertube-secret
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: peertube
      metadataPolicy: None
      property: PEERTUBE_SECRET
    secretKey: PEERTUBE_SECRET
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: peertube
      metadataPolicy: None
      property: PEERTUBE_DB_PASSWORD
    secretKey: PEERTUBE_DB_PASSWORD
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: peertube
      metadataPolicy: None
      property: PEERTUBE_SMTP_PASSWORD
    secretKey: PEERTUBE_SMTP_PASSWORD
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: peertube
      metadataPolicy: None
      property: POSTGRES_PASSWORD
    secretKey: POSTGRES_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: weyma-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: peertube-secret