apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: peertube-kv
  labels:
    app.kubernetes.io/instance: peertube
spec:
  anonymousAuth: true
  certIssuerType: ClusterIssuer
  clusterDomain: cluster.local
  clusterPreferredEndpointType: ip
  nodes: 1
  prometheus: false
  replicas: 3
  tls: false
  volumePermissions: true